### ISSUE TITLE
Detect links in PR titles

### ISSUE THREAD

**Issue by tjcorr** [danhellem/github-actions-pr-is-linked-to-work-item#165]
Right now the action is only able to detect AB#{id} links within a PR description. It would be nice to also support looking in the titles of the PRs as well.

**Comment by tjcorr** [comment]
Upon closer look at the code I can see this is not a trivial change to implement since the code is relying heavily on the Azure Boards app to verify the links rather than actually checking the ADO work item directly. Since the boards app can't add hyperlinks into titles this would require a complete overall of this action :/

**Comment by danhellem** [comment]
Yeah AB# does not currently work if in the title. Only the description. So this action would not help much in that case :(
