### ISSUE TITLE
Does this work with Fine-grained Permissions? 

### ISSUE THREAD

**Issue by lawrence31983** [danhellem/github-actions-pr-is-linked-to-work-item#76]
I would like to use this action but I keep getting 
![image](https://github.com/danhellem/github-actions-pr-is-linked-to-work-item/assets/30093301/386880ba-e0af-4c60-8b0d-7086bba9f27b)

When trying set it up with the permission changes in the documentation I'm unable to configure that setting even as the organization owner.

**Comment by danhellem** [comment]
@lawrence31983 did you follow the permissions section?

https://github.com/danhellem/github-actions-pr-is-linked-to-work-item#-permissions
